=== lawsoa70/bncs_pqtv_2020/config/device_description.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT device_description (param*)>
<!ATTLIST device_description
	name CDATA #REQUIRED
	family CDATA #IMPLIED
>
<!ELEMENT param ((values, display) | (state* | template) | (string))>
<!ATTLIST param
	name CDATA #REQUIRED
	class (enum | range | string | list) #REQUIRED
	slot CDATA #REQUIRED
	style CDATA #REQUIRED
	access (readwrite | readonly | writeonly) #REQUIRED
>
<!ELEMENT values EMPTY>
<!ATTLIST values
	min CDATA #REQUIRED
	max CDATA #REQUIRED
	step CDATA #REQUIRED
	bigstep CDATA #REQUIRED
	defaultvalue CDATA #REQUIRED
>
<!ELEMENT display EMPTY>
<!ATTLIST display
	inoffset CDATA #REQUIRED
	multiplier CDATA #REQUIRED
	outoffset CDATA #REQUIRED
	units CDATA #REQUIRED
	dp CDATA #REQUIRED
>
<!ELEMENT state EMPTY>
<!ATTLIST state
	value CDATA #REQUIRED
	caption CDATA #REQUIRED
	style CDATA #REQUIRED
	msg CDATA #REQUIRED
>
<!ELEMENT template EMPTY>
<!ATTLIST template
	id CDATA #REQUIRED
>
<!ELEMENT string EMPTY>
<!ATTLIST string
	maxlength CDATA #REQUIRED
	case (any | lower | upper | title) #REQUIRED
>

=== lawsoa70/bncs_pqtv_2020/config/devicetypes/gpi_outputs_48.xml
<?xml version = '1.0'?>
<!DOCTYPE device_description SYSTEM "device_description.dtd">
<device_description name="gpi_outputs_48" drivertype="GPI">
    <param class="enum" access="readonly" style="button" name="ISO1 Inhibit" slot="1">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO2 Inhibit" slot="2">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO3 Inhibit" slot="3">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO4 Inhibit" slot="4">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO5 Inhibit" slot="5">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO6 Inhibit" slot="6">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO7 Inhibit" slot="7">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO8 Inhibit" slot="8">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>

</device_description>

=== lawsoa70/bncs_pqtv_2020/config/devicetypes/gpi002_outputs.xml
<?xml version = '1.0'?>
<!DOCTYPE device_description SYSTEM "device_description.dtd">
<device_description name="gpi002_outputs" drivertype="INFODRIVER">
    <param class="enum" access="readonly" style="button" name="stc_ISO1 Inhibit" slot="1">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="stc_ISO2 Inhibit" slot="2">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="stc_ISO3 Inhibit" slot="3">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="stc_ISO4 Inhibit" slot="4">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="stc_ISO5 Inhibit" slot="5">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="stc_ISO6 Inhibit" slot="6">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="stc_ISO7 Inhibit" slot="7">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="stc_ISO8 Inhibit" slot="8">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>

</device_description>

=== lawsoa70/bncs_pqtv_2020/config/devicetypes/gpi001_inputs.xml
<?xml version = '1.0'?>
<!DOCTYPE device_description SYSTEM "device_description.dtd">
<device_description name="gpi001_inputs" drivertype="INFODRIVER">
    <param class="enum" access="readonly" style="label" name="sta_REH"               slot="1">
        <state caption="REH" style="topstrap_off" value="0" msg="" />
        <state caption="REH" style="topstrap_reh_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_TX"                slot="2">
        <state caption="TX" style="topstrap_off" value="0" msg="" />
        <state caption="TX" style="topstrap_tx_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_RedLights"         slot="3">
        <state caption="RED lights" style="topstrap_off" value="0" msg="" />
        <state caption="RED lights" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_FloorLights"       slot="4">
        <state caption="Disable|Floor Lights" style="topstrap_off" value="0" msg="" />
        <state caption="Enable|Floor Lights" style="topstrap_yellow_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_ReserveCleanDirty" slot="5">
        <state caption="Dirty|Reserve" style="topstrap_off" value="0" msg="" />
        <state caption="Clean|Reserve" style="topstrap_yellow_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_MainLU"            slot="6">
        <state caption="Main|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Main|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_ResLU"             slot="7">
        <state caption="Res|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Res|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_CleanLU"           slot="8">
        <state caption="Clean|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Clean|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_RingLU"            slot="9">
        <state caption="Ring|main|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Ring|main|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_ISO1LU"            slot="10">
        <state caption="ISO1|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO1|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_ISO2LU"            slot="11">
        <state caption="ISO2|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO2|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_ISO3LU"            slot="12">
        <state caption="ISO3|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO3|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_ISO4LU"            slot="13">
        <state caption="ISO4|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO4|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_VisionEcut"        slot="14">
        <state caption="E-CUT" style="topstrap_off" value="0" msg="" />
        <state caption="E-CUT" style="topstrap_ecut_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_VisionBypass"      slot="15">
        <state caption="BYPASS" style="topstrap_off" value="0" msg="" />
        <state caption="BYPASS" style="topstrap_bypass_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_SoundEcut"         slot="16">
        <state caption="E-CUT" style="topstrap_off" value="0" msg="" />
        <state caption="E-CUT" style="topstrap_ecut_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_SoundBypass"       slot="17">
        <state caption="BYPASS" style="topstrap_off" value="0" msg="" />
        <state caption="BYPASS" style="topstrap_bypass_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="sta_TB Mics"           slot="18">
        <state caption="TB Mics ON" style="topstrap_off" value="0" msg="" />
        <state caption="TB Mics OFF" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="sta_Vista1"            slot="19">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="sta_Vista2"            slot="20">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="sta_Vista3"            slot="21">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="sta_Vista4"            slot="22">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>

</device_description>

=== lawsoa70/bncs_pqtv_2020/config/devicetypes/ksc_gpi_inputs.xml
<?xml version = '1.0'?>
<!DOCTYPE device_description SYSTEM "device_description.dtd">
<device_description name="ksc_gpi_inputs" drivertype="GPI">
    <param class="enum" access="readonly" style="label" name="REH" slot="1">
        <state caption="REH" style="topstrap_off" value="0" msg="" />
        <state caption="REH" style="topstrap_reh_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="TX" slot="2">
        <state caption="TX" style="topstrap_off" value="0" msg="" />
        <state caption="TX" style="topstrap_tx_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="RedLights" slot="3">
        <state caption="RED lights" style="topstrap_off" value="0" msg="" />
        <state caption="RED lights" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="FloorLights" slot="4">
        <state caption="Disable|Floor Lights" style="topstrap_off" value="0" msg="" />
        <state caption="Enable|Floor Lights" style="topstrap_yellow_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="ReserveCleanDirty" slot="5">
        <state caption="Dirty|Reserve" style="topstrap_off" value="0" msg="" />
        <state caption="Clean|Reserve" style="topstrap_yellow_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="MainLU" slot="6">
        <state caption="Main|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Main|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="ResLU" slot="7">
        <state caption="Res|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Res|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="CleanLU" slot="8">
        <state caption="Clean|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Clean|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="RingLU" slot="9">
        <state caption="Ring|main|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Ring|main|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="ISO1LU" slot="10">
        <state caption="ISO1|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO1|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="ISO2LU" slot="11">
        <state caption="ISO2|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO2|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="ISO3LU" slot="12">
        <state caption="ISO3|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO3|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="ISO4LU" slot="13">
        <state caption="ISO4|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO4|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="VisionEcut" slot="14">
        <state caption="E-CUT" style="topstrap_off" value="0" msg="" />
        <state caption="E-CUT" style="topstrap_ecut_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="VisionBypass" slot="15">
        <state caption="BYPASS" style="topstrap_off" value="0" msg="" />
        <state caption="BYPASS" style="topstrap_bypass_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="SoundEcut" slot="16">
        <state caption="E-CUT" style="topstrap_off" value="0" msg="" />
        <state caption="E-CUT" style="topstrap_ecut_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="SoundBypass" slot="17">
        <state caption="BYPASS" style="topstrap_off" value="0" msg="" />
        <state caption="BYPASS" style="topstrap_bypass_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="TB Mics" slot="18">
        <state caption="TB Mics ON" style="topstrap_off" value="0" msg="" />
        <state caption="TB Mics OFF" style="" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="button" name="ISO1 Inhibit" slot="33">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO2 Inhibit" slot="34">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO3 Inhibit" slot="35">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO4 Inhibit" slot="36">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO5 Inhibit" slot="37">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO6 Inhibit" slot="38">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO7 Inhibit" slot="39">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="button" name="ISO8 Inhibit" slot="40">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="Vista1" slot="19">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="Vista2" slot="20">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="Vista3" slot="21">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="Vista4" slot="22">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>

</device_description>

=== lawsoa70/bncs_pqtv_2020/config/devicetypes/gpi002_inputs.xml
<?xml version = '1.0'?>
<!DOCTYPE device_description SYSTEM "device_description.dtd">
<device_description name="gpi002_inputs" drivertype="INFODRIVER">
    <param class="enum" access="readonly" style="label" name="stc_REH"               slot="1">
        <state caption="REH" style="topstrap_off" value="0" msg="" />
        <state caption="REH" style="topstrap_reh_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_TX"                slot="2">
        <state caption="TX" style="topstrap_off" value="0" msg="" />
        <state caption="TX" style="topstrap_tx_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_RedLights"         slot="3">
        <state caption="RED lights" style="topstrap_off" value="0" msg="" />
        <state caption="RED lights" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_FloorLights"       slot="4">
        <state caption="Disable|Floor Lights" style="topstrap_off" value="0" msg="" />
        <state caption="Enable|Floor Lights" style="topstrap_yellow_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_ReserveCleanDirty" slot="5">
        <state caption="Dirty|Reserve" style="topstrap_off" value="0" msg="" />
        <state caption="Clean|Reserve" style="topstrap_yellow_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_MainLU"            slot="6">
        <state caption="Main|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Main|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_ResLU"             slot="7">
        <state caption="Res|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Res|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_CleanLU"           slot="8">
        <state caption="Clean|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Clean|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_RingLU"            slot="9">
        <state caption="Ring|main|LU" style="topstrap_off" value="0" msg="" />
        <state caption="Ring|main|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_ISO1LU"            slot="10">
        <state caption="ISO1|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO1|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_ISO2LU"            slot="11">
        <state caption="ISO2|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO2|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_ISO3LU"            slot="12">
        <state caption="ISO3|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO3|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_ISO4LU"            slot="13">
        <state caption="ISO4|LU" style="topstrap_off" value="0" msg="" />
        <state caption="ISO4|LU" style="topstrap_red_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_VisionEcut"        slot="14">
        <state caption="E-CUT" style="topstrap_off" value="0" msg="" />
        <state caption="E-CUT" style="topstrap_ecut_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_VisionBypass"      slot="15">
        <state caption="BYPASS" style="topstrap_off" value="0" msg="" />
        <state caption="BYPASS" style="topstrap_bypass_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_SoundEcut"         slot="16">
        <state caption="E-CUT" style="topstrap_off" value="0" msg="" />
        <state caption="E-CUT" style="topstrap_ecut_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_SoundBypass"       slot="17">
        <state caption="BYPASS" style="topstrap_off" value="0" msg="" />
        <state caption="BYPASS" style="topstrap_bypass_on" value="1" msg="" />
	</param>
    <param class="enum" access="readonly" style="label" name="stc_TB Mics"           slot="18">
        <state caption="TB Mics ON" style="topstrap_off" value="0" msg="" />
        <state caption="TB Mics OFF" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="stc_Vista1"            slot="19">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="stc_Vista2"            slot="20">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="stc_Vista3"            slot="21">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>
	<param class="enum" access="readonly" style="label" name="stc_Vista4"            slot="22">
        <state caption="Cues On" style="" value="0" msg="" />
        <state caption="Cues Off" style="" value="1" msg="" />
	</param>

</device_description>
