=== lawsoa70/bncs_pqtv_2020/config/panelsets.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT panelsets (set+)>
<!ELEMENT set (item+)>
<!ATTLIST set
	id CDATA #REQUIRED
	level CDATA #REQUIRED
>
<!ELEMENT item EMPTY>
<!ATTLIST item
	id CDATA #REQUIRED
	param CDATA #REQUIRED
>

=== lawsoa70/bncs_pqtv_2020/config/panelsets.xml
<?xml version="1.0" ?>
<!DOCTYPE panelsets SYSTEM "panelsets.dtd">
<panelsets>
	<!-- Studio A -->
	<set id="sta_Eng_Man" level="user" popup="true">
		<item id="studio_a/em_mons_left"            class="application" param=""/>
		<item id="studio_a/em_audio"                class="application" param=""/>
		<item id="studio_a/pcr_stack"               class="application" param=""/>
		<item id="studio_a/floor_previews"          class="application" param=""/>
		<item id="studio_a/pcr_audio_mon"           class="application" param=""/>
		<item id="studio_a/iso"                     class="application" param=""/>
		<item id="studio_a/mv_inputs"               class="application" param=""/>
		<item id="studio_a/vt_inputs"               class="application" param=""/>
		<item id="studio_a/vision_bypass"           class="application" param=""/>
		<item id="studio_a/SoftNameSummary_sta"     class="application" param=""/>
		<item id="studio_a/SoftNameLocal_sta"       class="application" param=""/>
		<item id="studio_a/SoftNameSncs_sta"        class="application" param=""/>
		<item id="studio_a/SoftNameExternal_sta"    class="application" param=""/>
		<item id="studio_a/iso_inhibits"            class="application" param=""/>
	</set>
	<set id="sta_Eng_Man_eng" level="user" popup="true">
		<item id="studio_a/comms_os_listen"         class="application" param=""/>
		<item id="studio_a/comms_clean_feed"        class="application" param=""/>
		<item id="studio_a/iso_inhibits"            class="application" param=""/>
		<item id="router_xy/studio_a_sdi_list"      class="application" param=""/>
		<item id="studio_a/sdi_router_mapping"      class="application" param=""/>
		<item id="studio_a/vista_mixer"             class="application" param=""/>
	</set>
	<set id="sta_Snd_Sup" level="user" popup="true">
		<item id="studio_a/comms_clean_feed"        class="application" param=""/>
		<item id="studio_a/scr_stack"               class="application" param=""/>
		<item id="studio_a/grams_desk"              class="application" param=""/>
		<item id="studio_a/grams_machine"           class="application" param=""/>
		<item id="studio_a/scr_bay_mon"             class="application" param=""/>
		<item id="studio_a/comms_highways"          class="application" param=""/>
		<item id="studio_a/embedder_inputs"         class="application" param=""/>
		<item id="studio_a/sound_bypass"            class="application" param=""/>
		<item id="studio_a/pcr_audio_mon"           class="application" param=""/>
		<item id="studio_a/protools"                class="application" param=""/>
	</set>
	<set id="sta_Grams" level="user" popup="true">
		<item id="studio_a/comms_clean_feed"        class="application" param=""/>
		<item id="studio_a/scr_stack"               class="application" param=""/>
		<item id="studio_a/grams_desk"              class="application" param=""/>
		<item id="studio_a/grams_machine"           class="application" param=""/>
		<item id="studio_a/scr_bay_mon"             class="application" param=""/>
		<item id="studio_a/comms_highways"          class="application" param=""/>
		<item id="studio_a/protools"                class="application" param=""/>
	</set>
	<set id="sta_Snd_Bay" level="user" popup="true">
		<item id="studio_a/comms_clean_feed"        class="application" param=""/>
		<item id="studio_a/scr_stack"               class="application" param=""/>
		<item id="studio_a/grams_desk"              class="application" param=""/>
		<item id="studio_a/grams_machine"           class="application" param=""/>
		<item id="studio_a/scr_bay_mon"             class="application" param=""/>
		<item id="studio_a/comms_highways"          class="application" param=""/>
		<item id="studio_a/protools"                class="application" param=""/>
	</set>
	<set id="sta_Snd_eng" level="user" popup="true">
		<item id="studio_a/embedder_inputs"         class="application" param=""/>
		<item id="studio_a/sound_bypass"            class="application" param=""/>
		<item id="studio_a/pcr_audio_mon"           class="application" param=""/>
		<item id="studio_a/audio_router_mapping"    class="application" param=""/>
		<item id="studio_a/comms_os_listen"         class="application" param=""/>
		<item id="router_xy/studio_a_nexus_list"    class="application" param=""/>
		<item id="studio_a/em_audio"                class="application" param=""/>
		<item id="studio_a/vaa_audio"               class="application" param=""/>
		<item id="studio_a/floor_previews"          class="application" param=""/>
		<item id="studio_a/mv_inputs"               class="application" param=""/>
		<item id="studio_a/vision_bypass"           class="application" param=""/>
		<item id="router_xy/studio_a_sdi_list"      class="application" param=""/>
		<item id="studio_a/vision_spares"           class="application" param=""/>
		<item id="studio_a/vt_inputs"               class="application" param=""/>
		<item id="studio_a/sdi_router_mapping"      class="application" param=""/>
		<item id="studio_a/pcr_stack"               class="application" param=""/>
		<item id="studio_a/em_mons_left"            class="application" param=""/>
		<item id="studio_a/vista_mixer"             class="application" param=""/>
		<item id="studio_a/iso"                     class="application" param=""/>
	</set>
	<set id="sta_Vis_Mix" level="user" popup="true">
		<item id="studio_a/em_mons_right"           class="application" param=""/>
		<item id="studio_a/em_audio"                class="application" param=""/>
		<item id="studio_a/pcr_stack"               class="application" param=""/>
		<item id="studio_a/mv_inputs"               class="application" param=""/>
		<item id="studio_a/floor_previews"          class="application" param=""/>
		<item id="studio_a/pcr_audio_mon"           class="application" param=""/>
		<item id="studio_a/iso"                     class="application" param=""/>
		<item id="studio_a/iso_inhibits"            class="application" param=""/>
		<item id="studio_a/vt_inputs"               class="application" param=""/>
		<item id="studio_a/vision_bypass"           class="application" param=""/>
		<item id="studio_a/vista_mixer"             class="application" param=""/>
		<item id="studio_a/SoftNameLocal_sta"       class="application" param=""/>
		<item id="studio_a/SoftNameSncs_sta"        class="application" param=""/>
		<item id="studio_a/SoftNameExternal_sta"    class="application" param=""/>
		<item id="studio_a/SoftNameSummary_sta"     class="application" param=""/>
		<item id="studio_a/em_audio"                class="application" param=""/>
		<item id="studio_a/pcr_audio_mon"           class="application" param=""/>
	</set>
	<set id="sta_Vis_Mix_eng" level="user" popup="true">
		<item id="studio_a/iso"                     class="application" param=""/>
		<item id="studio_a/iso_inhibits"            class="application" param=""/>
		<item id="studio_a/vt_inputs"               class="application" param=""/>
		<item id="studio_a/vision_bypass"           class="application" param=""/>
		<item id="studio_a/SoftNameLocal_sta"       class="application" param=""/>
		<item id="studio_a/SoftNameSncs_sta"        class="application" param=""/>
		<item id="studio_a/SoftNameExternal_sta"    class="application" param=""/>
		<item id="studio_a/SoftNameSummary_sta"     class="application" param=""/>
		<item id="studio_a/comms_os_listen"         class="application" param=""/>
		<item id="studio_a/comms_clean_feed"        class="application" param=""/>
		<item id="router_xy/studio_a_sdi_grid"      class="application" param=""/>
		<item id="router_xy/studio_a_sdi_list"      class="application" param=""/>
		<item id="studio_a/sdi_router_mapping"      class="application" param=""/>
		<item id="router_xy/studio_a_sdi_ip_list"   class="application" param=""/>
		<item id="studio_a/sdi_router_mapping_ip"   class="application" param=""/>
	</set>
	<set id="sta_LVCR" level="user" popup="true">
		<item id="studio_a/lvcr_stack"              class="application" param=""/>
		<item id="studio_a/pcr_stack"               class="application" param=""/>
		<item id="studio_a/mv_inputs"               class="application" param=""/>
		<item id="studio_a/floor_previews"          class="application" param=""/>
		<item id="studio_a/SoftNameSummary_sta"     class="application" param=""/>
		<item id="studio_a/SoftNameLocal_sta"       class="application" param=""/>
		<item id="studio_a/SoftNameSncs_sta"        class="application" param=""/>
		<item id="studio_a/SoftNameExternal_sta"    class="application" param=""/>
		<item id="studio_a/rcp_assign"              class="application" param=""/>
	</set>
	<set id="sta_LVCR_eng" level="user" popup="true">
		<item id="router_xy/studio_a_sdi_list"      class="application" param=""/>
		<item id="studio_a/iso_inhibits"            class="application" param=""/>
		<item id="studio_a/iso"                     class="application" param=""/>
		<item id="studio_a/embedder_inputs"         class="application" param=""/>
		<item id="studio_a/vt_inputs"               class="application" param=""/>
		<item id="studio_a/sir_mons"                class="application" param=""/>
		<item id="studio_a/vlcr_audio"              class="application" param=""/>
		<item id="router_xy/studio_a_nexus_list"    class="application" param=""/>
		<item id="router_xy/studio_a_sdi_grid"      class="application" param=""/>
		<item id="router_xy/studio_b_sdi_list"      class="application" param=""/>
		<item id="studio_b/SoftNameSummary_stb"     class="application" param=""/>
		<item id="studio_b/SoftNameLocal_stb"       class="application" param=""/>
		<item id="studio_b/SoftNameSncs_stb"        class="application" param=""/>
		<item id="studio_b/SoftNameExternal_stb"    class="application" param=""/>
		<item id="router_xy/studio_a_sdi_list"      class="application" param=""/>
		<item id="router_xy/studio_b_sdi_list"      class="application" param=""/>
		<item id="router_xy/studio_c_sdi_list"      class="application" param=""/>
